log-topic-set:
  - be.normal
  - be.mybatis
  - be.mybatis.insert
not-log-topic-set:
  - org.apache.kafka.clients.consumer.ConsumerConfig
  - com.kar20240901.be.base.web.mapper.request.BaseRequestMapper.insert
  - com.kar20240901.be.base.web.mapper.request.BaseRequestInfoMapper.insert
  - com.kar20240901.be.base.web.mapper.base.BaseUserInfoMapper.updateById
  - com.kar20240901.be.base.web.mapper.socket.BaseSocketRefUserMapper.insert